### ISSUE TITLE
Performance: Reduce Log Output

### ISSUE THREAD

**Issue by MartinHaeusler** [Synthesis-Collective/SynthesisRPGLoot#38]
I have a fairly large mod list (850+), among them also several armor mods. This naturally causes the patcher to produce a lot of items due to the combinatory explosion of rarities, enchantments, and items. I've got the feeling that the speed of the patcher is held back by the excessive amount of logging (every produced item is logged twice, once as a "start" and once as a "finished" entry). This results in over 10 megabytes of logs in my case from this patcher alone. Maybe compute the total number of items to generate upfront and only log percentage progress? (e.g. "1%...2%...") and only report concrete item names if there's an error?

It's just my gut feeling, I don't have any profiling data to back this up. Feel free to disregard if you think that this is not the issue.

**Comment by EzioTheDeadPoet** [comment]
Oh yeah this actually valid. 
Main Issue I have with disabling the log is that even if it could speed up the launcher by a significant amount of time a lot of less advanced users would assume that the patcher is stuck since it will still take a long time to generate an output compared to other patchers even ones with logging. 

But I just got the idea to make it a toggle in the settings to disable logging. And reduce the amount of unnecessary logs. 
Additionally I think I am very close to releasing 4.0.0 soon officially.

**Comment by EzioTheDeadPoet** [comment]
I just went ahead and cleaned the logs and added the option.
